import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// Autogenerated from the folders under docs/. Add a folder with a
// _category_.json to add a section; order comes from sidebar_position.
const sidebars: SidebarsConfig = {
  voiceboxSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
